---
- name: Add Google Chrome key
  ansible.builtin.apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present

- name: Remove old Google Chrome repo
  ansible.builtin.apt_repository:
    repo: "deb http://dl.google.com/linux/chrome/deb/ stable main"
    state: absent
    filename: "google-chrome"

- name: Add Google Chrome repo
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main"
    state: present
    filename: "google-chrome"

- name: Install Google Chrome
  ansible.builtin.apt:
    name: google-chrome-stable
    state: present
    update_cache: true
  ignore_errors: "{{ ansible_check_mode }}"
